
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 12 21:12:53 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SPACE = 49;
  public static final int CONST = 6;
  public static final int ASTERISK = 28;
  public static final int NAMESPACE = 5;
  public static final int LPAREN = 19;
  public static final int SEMI = 9;
  public static final int CONTINUE = 25;
  public static final int MINUS = 42;
  public static final int FOR = 27;
  public static final int STATIC = 10;
  public static final int RPAREN = 20;
  public static final int AND = 32;
  public static final int LT = 39;
  public static final int OR = 31;
  public static final int COMMA = 8;
  public static final int GET = 38;
  public static final int EQUALEQUAL = 35;
  public static final int INC = 29;
  public static final int PLUS = 41;
  public static final int IF = 22;
  public static final int DOT = 34;
  public static final int LBOXBRAC = 17;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int EQUAL = 7;
  public static final int IDENTCOLCOL = 50;
  public static final int TRUE = 12;
  public static final int NEW = 33;
  public static final int error = 1;
  public static final int PERCENT = 44;
  public static final int NUMBER = 11;
  public static final int BREAK = 23;
  public static final int IDENT = 14;
  public static final int VOID = 43;
  public static final int COL = 21;
  public static final int LBRACE = 3;
  public static final int ELSE = 24;
  public static final int LETTER = 16;
  public static final int READ = 47;
  public static final int LET = 40;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 15;
  public static final int PROG = 2;
  public static final int DIFF = 36;
  public static final int DEC = 30;
  public static final int FALSE = 13;
  public static final int DIVISION = 45;
  public static final int RBOXBRAC = 18;
  public static final int FOLLOWS = 48;
  public static final int GT = 37;
  public static final int PRINT = 46;
}

