
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 08 13:12:33 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 16;
  public static final int NAMESPACE = 41;
  public static final int LPAREN = 6;
  public static final int SEMI = 3;
  public static final int CONTINUE = 32;
  public static final int FOR = 40;
  public static final int MINUS = 11;
  public static final int CHARACTER = 45;
  public static final int STATIC = 36;
  public static final int RPAREN = 7;
  public static final int GRE = 23;
  public static final int AND = 18;
  public static final int LS = 24;
  public static final int OR = 19;
  public static final int BOOL = 46;
  public static final int COMMA = 27;
  public static final int LSE = 25;
  public static final int INC = 29;
  public static final int DIV = 13;
  public static final int PLUS = 15;
  public static final int IF = 38;
  public static final int THIS = 2;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int RETURN = 33;
  public static final int EQUAL = 10;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int MUL = 12;
  public static final int NUMBER = 44;
  public static final int MOD = 14;
  public static final int IDENT = 43;
  public static final int BREAK = 31;
  public static final int VOID = 37;
  public static final int LBRACK = 4;
  public static final int COLON = 26;
  public static final int ELSE = 39;
  public static final int LBRACE = 8;
  public static final int READ = 34;
  public static final int RBRACK = 5;
  public static final int RBRACE = 9;
  public static final int PROG = 42;
  public static final int DEC = 30;
  public static final int GR = 22;
  public static final int PRINT = 35;
  public static final int ISEQ = 20;
  public static final int NOTEQ = 21;
}

