
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 07 20:54:47 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SPACE = 47;
  public static final int CONST = 6;
  public static final int ASTERISK = 26;
  public static final int NAMESPACE = 5;
  public static final int LPAREN = 17;
  public static final int SEMI = 9;
  public static final int CONTINUE = 23;
  public static final int MINUS = 40;
  public static final int FOR = 25;
  public static final int STATIC = 10;
  public static final int RPAREN = 18;
  public static final int AND = 30;
  public static final int LT = 37;
  public static final int OR = 29;
  public static final int COMMA = 8;
  public static final int GET = 36;
  public static final int INC = 27;
  public static final int EQUALEQUAL = 33;
  public static final int PLUS = 39;
  public static final int IF = 20;
  public static final int DOT = 32;
  public static final int LBOXBRAC = 15;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int EQUAL = 7;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int PERCENT = 42;
  public static final int NUMBER = 11;
  public static final int BREAK = 21;
  public static final int IDENT = 12;
  public static final int VOID = 41;
  public static final int COL = 19;
  public static final int LBRACE = 3;
  public static final int ELSE = 22;
  public static final int LETTER = 14;
  public static final int READ = 45;
  public static final int LET = 38;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 13;
  public static final int PROG = 2;
  public static final int DIFF = 34;
  public static final int DEC = 28;
  public static final int DIVISION = 43;
  public static final int RBOXBRAC = 16;
  public static final int FOLLOWS = 46;
  public static final int GT = 35;
  public static final int PRINT = 44;
}

